import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    linterOptions: {
      reportUnusedDisableDirectives: "warn",
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-unused-vars": "warn",
      "@next/next/no-img-element": "warn",
      "import/no-anonymous-default-export": "warn",
      "prefer-const": "warn",
      "react-hooks/immutability": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/set-state-in-effect": "warn",
      "react/no-children-prop": "warn",
      "react/no-unescaped-entities": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    "next-env.d.ts",
    // Local agent/runtime bundles are not application source.
    ".agents/**",
    ".claude/**",
    ".opencode/**",
    // Local skill bundles are not part of the runtime app source.
    ".codex/**",
    // Docs, reports, and source data exports are audited separately.
    "assets/**",
    "data/**",
    "docs/**",
    "log/**",
    "plans/**",
    "prompt/**",
    "reports/**",
    // QA artifacts and temporary test files generated by automation.
    "plans/.qa-artifacts/**",
    "tests/**",
    "**/*.cjs",
    // Temporary Chrome profiles and other local tooling artifacts.
    ".tmp/**",
    ".tmp-*/**",
    "tmp-*",
  ]),
]);

export default eslintConfig;
