ALTER TYPE "LifecycleEmailType" ADD VALUE IF NOT EXISTS 'TRIAL_D1';
ALTER TYPE "LifecycleEmailType" ADD VALUE IF NOT EXISTS 'TRIAL_D5';
ALTER TYPE "LifecycleEmailType" ADD VALUE IF NOT EXISTS 'WINBACK_D30';
ALTER TYPE "LifecycleEmailType" ADD VALUE IF NOT EXISTS 'RENEWAL_14D';

